SELECT 
    ORD.ORDER_ID,
    CONCAT(CUS.FIRST_NAME, ' ', CUS.LAST_NAME) AS 'CUSTOMERS',
    CUS.CITY,
    CUS.STATE,
    ORD.ORDER_DATE,
    SUM(ITE.QUANTITY) AS 'TOTAL_UNITS',
    SUM(ITE.QUANTITY * ITE.LIST_PRICE) AS REVENUE,
    PRO.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    STO.STORE_NAME,
    CONCAT(STA.FIRST_NAME, ' ', STA.LAST_NAME) AS 'SALES_REP'
FROM
    SALES.ORDERS ORD
        JOIN
    SALES.CUSTOMERS CUS ON ORD.CUSTOMER_ID = CUS.CUSTOMER_ID
        JOIN
    SALES.ORDER_ITEMS ITE ON ORD.ORDER_ID = ITE.ORDER_ID
        JOIN
    PRODUCTION.PRODUCTS PRO ON ITE.PRODUCT_ID = PRO.PRODUCT_ID
        JOIN
    PRODUCTION.CATEGORIES CAT ON PRO.CATEGORY_ID = CAT.CATEGORY_ID
        JOIN
    SALES.STORES STO ON ORD.STORE_ID = STO.STORE_ID
        JOIN
    SALES.STAFFS STA ON ORD.STAFF_ID = STA.STAFF_ID
GROUP BY ORD.ORDER_ID , CONCAT(CUS.FIRST_NAME, ' ', CUS.LAST_NAME) , CUS.CITY , CUS.STATE , ORD.ORDER_DATE , PRO.PRODUCT_NAME , CAT.CATEGORY_NAME , STO.STORE_NAME , CONCAT(STA.FIRST_NAME, ' ', STA.LAST_NAME);

